name: Deploy Sonace API to EC2

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          NODE_OPTIONS="--max-old-space-size=2048" npm run build

      - name: Archive production files
        run: |
          mkdir deploy
          cp -r package.json package-lock.json dist deploy/
          cd deploy && zip -r sonace-api.zip .

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts  # Removed the quotes around ${{ secrets.EC2_HOST }}

      - name: Transfer build to EC2
        run: |
          scp deploy/sonace-api.zip ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:~/sonace-api.zip

      - name: Run deploy script on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} 'bash ~/deploy_sonace.sh'
